name: gerry
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python=3.7
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - bokeh
  - gurobi
  - seaborn
  - geopandas
  - shapely
  - geopy
  - nb_conda
  - ipykernel
  - networkx
  - pysal
  - tqdm
  - requests
  - flask
